### ISSUE TITLE
Server Side Scripting

### ISSUE THREAD

**Issue by zamanak** [dreamfactorysoftware/df-core#26] opened 2016-11-01 12:25 UTC
Hi,
I have created a service `X`(NodeJs Server Side Script) and follow [Setting up guest access](http://wiki.dreamfactory.com/DreamFactory/Tutorials/Setting_up_guest_access) to let `X` be a guest service and public, so everyone can access it.

In service `X` i want to call some internal api, for example(`/mysql/_table/testtable`), so for this purpose i have a role `R` that have access to `/mysql/_table/*` service with all access types(get,post,put,...) and requestor(`SCRIPT`) and also `X` with requestor(`API`) access:

#### App `A`:
app `A` have default role `R`

#### Role `R`:

Service | Componnent | Access | Requestor
------------ | ------------- | ------------- | -------------
`X` | * | All | `API`
`mysql` | `_table/*` | All | `SCRIPT`

#### Service `X`:

```javascript
//some code ...
platform.api.post('/mysql/_table/testtable', {
	"resource": [
		{
			"a": ".....",
			"b": ".....",
			"c": "....."
		}
	]
},
'', 
function(body, response){
	//in this place i receive 401 status code
});
//some code ...
```

When call `X` and `X` call those `internal api`  i receive `Unauthorized. User is not authenticated.`

But when change requestor of `mysql` service to `SCRIPT and API` everything is ok!

I`ve look at df-core and guess this is a core bug!

What is the problem?

thanks

**Comment by leehicks** [comment] 2016-11-01 13:54
Confirmed this is a two part bug. The first being that node.js and python script calls to other services are not being "seen" as script calls. The second being that the error should be 403 instead of 401 when guest access is denied (which wouldn't be the case if the first issue were fixed). We will get both filed and in the backlog.

**Comment by zamanak** [comment] 2016-11-02 05:47
thanks @leehicks

**Comment by srobati** [comment] 2016-11-03 19:21
@leehicks please tell the approximate time for fixing this bug if possible.

**Comment by leehicks** [comment] 2017-09-07 18:16
This has been fixed in the spin off repo, df-script, since its 0.2.0  version. We now employ a token and cache system for NodeJs and Python to make "internal" scripting calls back into DreamFactory.

**Closed by leehicks** 2017-09-07 18:16 UTC
